version: "3.9"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "localdb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "8080:3306"
    expose:
      - "3306"
    volumes:
      - local-db:/var/lib/mysql
volumes:
  local-db:
